import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import Card from './components/Card'
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import React from "react";
import { AuthProvider } from "./context/loginContext/LoginContext";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <React.StrictMode>
          <AuthProvider>
            <Navbar />

            {children}

            <Footer />
          </AuthProvider>
        </React.StrictMode>
      </body>
    </html>
  );
}
